Updated RPV docs
eradiate/eradiate-kernel pull request #4
Opened 2021-01-12 10:46 UTC by schunkes

## Description

The RPV docs were updated to match the actual implementation.
The docs refer to the parameter `g` everywhere instead of `Theta`.
The docs no longer mention multiple extensions and refer the user to the scientific handbook
for details on the implementation.

The only question is: Is is correct to refer to Raytran in the way I did here?

Fixes # (issue) [eradiate/eradiate-issues/#33](https://gihub.com/eradiate/eradiate-issues/#33)

## Testing

None

## Checklist:

*Please make sure to complete this checklist before requesting a review.*

- [ ] My code follows the [style guidelines](https://mitsuba2.readthedocs.io/en/latest/src/developer_guide/intro.html#introduction) of this project
- [ ] My changes generate no new warnings
- [ ] My code also compiles for `gpu_*` and `packet_*` variants. If you can't test this, please leave below
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I cleaned the commit history and removed any "Merge" commits
- [ ] I give permission that the Mitsuba 2 project may redistribute my contributions under the terms of its [license](https://github.com/mitsuba-renderer/mitsuba2/blob/master/LICENSE)

2021-01-20 10:02 UTC, leroyvn requested changes
Hi @schunkes, thanks for taking care of that.

> Is is correct to refer to Raytran in the way I did here?

Not if you expect people to then be able to track back your reference. At least citing a scientific article would be more "by the book" (this is the reference [Raytran paper](https://ieeexplore.ieee.org/abstract/document/662732)). But this article doesn't mention RPV, and I think this is JRC's work, then published under the name RaySpread in [another paper](https://link.springer.com/chapter/10.1007%2F3-540-28125-8_10). In both cases anyway, the equations are missing from the paper.

The RaySpread paper is probably the best reference we have now. You can add it to the BibTeX file and cite it, that should do the job.

2021-02-09 09:31 UTC, leroyvn commented
Hi @schunkes, any progress on this?

2021-03-10 09:39 UTC, schunkes commented
I pushed an update, adding a reference to the Rayspread project.

2021-03-10 13:27 UTC, leroyvn commented
Alright, let's squash and merge this!

2021-03-11 10:53 UTC, merged